### PR TITLE
#161290889 AuthorsHaven database setup

### PR DESCRIPTION
**Pull request by ajimae**
#### What does this PR do?

- Configure Authors Haven to use PostgreSQL as DB Engine

#### Description of Task to be completed?

- setup sequelize, sequelize-cli and .sequelizerc files
- generate models, migration files and config File
- include a .env file to store database credentials
- add scripts to the package.json file to migrate 
database and drop database tables respectively
- add a babelHook.js file to handle ES6 synthax for sequelize
- update the babelrc to include module export plugins
- install babel-register, babel-plugin-add-module-exports
sequelize-cli modules, pg, pg-hstore, sequelize modules
- git ignore .env file

#### How should this be manually tested?

- Clone this repository
- On terminal, run `npm install` to install modules and dependencies
- On terminal, run `npm run migrate` or `npm run clean-db` to migrate or drop database tables

#### Any background context you want to provide?

**babel-plugin-add-module-exports** and **sequelize-cli** are both installed as dev-dependencies
More about sequelize can be found here [Sequelize](http://docs.sequelizejs.com)

#### What are the relevant pivotal tracker stories?

[#161290889](https://www.pivotaltracker.com/story/show/161290889)

#### Screenshot

image

### CODE REVIEW

**Comment by oluseyianani** [comment]
Hello @ajimae, this branch still has a conflict that needs to be resolved.

**Comment by hope-uwa** [comment]
You should add `npm install` to how it can be manually tested on your PR message

**Comment by desaawa** [comment]
@ajimae ensure that all the endpoints that were working before are still working after you made the changes

**Comment by ajimae** [comment]
> Hello @ajimae, this branch still has a conflict that needs to be resolved.

I have fixed it.

**Comment by ajimae** [comment]
> @ajimae ensure that all the endpoints that were working before are still working after you made the changes

Okay, Awa,
I did just as you said, all the predefined endpoints are all working.

**Comment by ajimae** [comment]
> You should add `npm install` to how it can be manually tested on your PR message

Done.

**Comment by oluseyianani** [comment]
@ajimae .env.sample file's content is missen. I think it's essential to add this as well so users can be able to configure their database's environment correctly.

**Review by desaawa — APPROVED** [review]

**Pull request merged**
