### PR TITLE
#161290913 Update Search Functionality

### PR DESCRIPTION
**Pull request by ovieokeh**
#### What does this PR do?
This PR updates search functionality to the Authors Haven API. Search can now be filtered by tags.

- Add ability to filter the search by tags only
- Add ability to filter the search by both tags and authors
- Add tests to ensure that the feature works as expected
- Move SQL query to separate file
- Move calls to the DB to separate file

#### Description of Task to be completed?
- `/POST 200 OK - /search`
    --- Required field: `keywords`

##### Filtering by tags only
1. After adding your search term in the `keywords` field
2. Add `?tags=<tags_to_filter_by>` to the URL where `<tags_to_filter_by>` is the tags you want to filter by (check the screenshots section for more information)
3. Now you will only get a result if the article matching the search term also has the tags specified

##### Filtering by both tags and authors
1. After adding your search term in the `keywords` field
2. Add `?author=<author_of_article>&tags=<tags_to_filter_by>` to the URL where `<author_of_article` is the author whose articles you want and `<tags_to_filter_by>` is the tags you want to filter by (check the screenshots section for more information)
3. Now you will only get a result if the article with the search term was posted by the author being queried and if the article matching the search term also has the tags specified

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#161290913

#### Screenshots (if appropriate)
screen shot 2018-11-12 at 4 49 12 pm
screen shot 2018-11-12 at 4 48 59 pm

#### Questions:
N/A

### CODE REVIEW

**Review by oluseyianani — COMMENTED** [review]
Nicely refactored.

**Review by oluseyianani — APPROVED** [review]
Nicely refactored.

**Review by hope-uwa — APPROVED** [review]

**Review by hope-uwa — COMMENTED** [review]
Great job @65black

**Review by ajimae — APPROVED** [review]

**Review by desaawa — APPROVED** [review]
Please resolve conflicts and merge.

**Pull request merged**
