### PR TITLE
#161290905 Enable users comment on article

### PR DESCRIPTION
**Pull request by Frediflexta**
#### What does this PR do?
* It enables a user comment on an article and also reply a comment
#### Description of Task to be completed?
- Establish a model relationship between comments, users and articles table
- Establish a model relationship between reply to comments and comments and users table
- Enable users to reply to comments
- Create comments
- Read comments when articles are returned
- Update comments
- Delete comment
#### How should this be manually tested?
- Clone the repo from `develop` run `npm install`
- Start the app by runing `npm run dev` 
- Create users by following this instruction  #11 
- Create an article by POST `http://localhost:3000/api/v1/articles`
- POST a comment via `http://localhost:3000/api/v1/articles/:articleId/comments`
- Visit `http://localhost:3000/api/v1/articles/:commentId/` and send a POST request
to reply a comment simply `http://localhost:3000/api/v1/comments/:commentId/replies`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
* #161290905
#### Screenshots (if appropriate)
screen shot 2018-11-19 at 2 44 29 pm
screen shot 2018-11-19 at 2 45 28 pm

#### Questions:
N/A

### CODE REVIEW

**Review by oluseyianani — CHANGES_REQUESTED** [review]
Looked through the code and I think everything looks good. However, on your pull request text on ###How should this be manually tested?###, I think the steps required to test this functionality isn't properly listed, take for instance, having to install all the necessary packages, having to create users and articles before actually making comments. You can try to make this adjustment. Aside from this, everything looks good. Great job @Frediflexta

**Review by oluseyianani — APPROVED** [review]

**Review by ovieokeh — APPROVED** [review]
Looks good.

**Review by ajimae — APPROVED** [review]
Awesome job @Frediflexta. Well spelled out PR comments, it's not just elaborate, it is also straight to the point. However, your cases and capitalizations are a bit inconsistent.

See below for some suggested corrections.

**Description of Task to be completed?** the first characters of each list should be capitalized.

Example: Rather than **establish model relationship between comments, users and articles table** you should capitalize the **e** in establish to read **Establish model relationship between comments, users and articles table**

**How should this be manually tested?** here, there are some inconsistencies in the capitalizations, looking at the fourth list, the **c** in create is not capitalized as against other lists within this category which were all capitalized. This will enable your write-ups to be consistent and easy to read thereby giving the PR comment good grammatical credibility.  Aside these every other thing is okay.

Try effecting these changes and if you need further help, am always available.

**Comment by ajimae** [comment]
Great job @Frediflexta.

**Review by desaawa — APPROVED** [review]
lgtm

**Pull request merged**
