### PR TITLE
#161290901 Enable Social Media Login 

### PR DESCRIPTION
**Pull request by Frediflexta**
#### What does this PR do?
* Enables users to signup or sign in through google and facebook
#### Description of Task to be completed?
* When a user wants to be a registered member of Authors Haven, they have the option of registering or logging in through their facebook or google account.
#### How should this be manually tested?
* On your browser
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#161290901
#### Screenshots (if appropriate)
screen shot 2018-11-27 at 7 43 02 pm
screen shot 2018-11-27 at 7 43 18 pm

#### Questions:
N/A

### CODE REVIEW

**Review by ajimae — APPROVED** [review]

**Comment by desaawa** [comment]
@Frediflexta is this still WIP?

**Review by oluseyianani — COMMENTED** [review]
Looks good @Frediflexta. Nice job!

**Review by oluseyianani — APPROVED** [review]

**Comment by Frediflexta** [comment]
@awadesmoline Yes it was, and I explained what was still being worked on when we had our TTL interaction this morning. I am done with the feature now though, it can now sign a users' information and issue a token, and I also set the token to the response header.

**Comment by desaawa** [comment]
hey @Frediflexta, please resolve the conflicts here and merge.

**Review by desaawa — APPROVED** [review]

**Pull request merged**
