### PR TITLE
#161290917- Report an article

### PR DESCRIPTION
**Pull request by hope-uwa**
#### What does this PR do?
- Implements report an article feature

####Description of Task to be completed?
- creates migration table for reports
- creates model and association for reports
- creates validation helpers creating report and updating reports
- creates workers for report database calls.
- creates report controller
- creates routes
*POST* `/api/v1/articles/<slug>/report`
*GET* `/api/v1/reports`
*PUT* `/api/v1/reports/<reportId>/resolve`

- creates helpers for HTTP response
- install Sinon for unit testing
- 100% test coverage for HTTP response and report controllers.

#### How should this be manually tested?
- cloning this repo,
- cd into it on command/shell
- run npm install to install all the dependencies and dev-dependencies.
- Create a .env file and add credentials as described on the .env.sample file.
- run npm run test-dev on command to run test
- To test the endpoint on Postman run npm run dev 
- create users #11 
- create article #13 
- use the routes post report route above

#### Any background context you want to provide?
- Only authenticated users can post a report
- viewing and resolving report actions are for admin users

#### What are the relevant pivotal tracker stories?
- #161290917
#### Screenshots (if appropriate)
screen shot 2018-11-16 at 8 00 40 am

#### Questions:
- N/A

### CODE REVIEW

**Review by oluseyianani — CHANGES_REQUESTED** [review]
Something's not right here.

**Review by Frediflexta — COMMENTED** [review]
Please take a look at the files conflicting and resolve them.

**Review by ovieokeh — APPROVED** [review]
Thanks for refactoring the http responses into a helper. It really helps.

**Review by oluseyianani — APPROVED** [review]

**Review by desaawa — APPROVED** [review]
Resolve conflicts and merge.

**Pull request merged**
