### PR TITLE
#161785827 Fix server files to build on production

### PR DESCRIPTION
**Pull request by oluseyianani**
#### What does this PR do?
- Rebase off two initial branches
- Added the distribution folder `dist/` in `.gitignore`.
- Adjust the script file on `package.json`

#### Description of Task to be completed?
- Make the app run on production
#### How should this be manually tested?
- After cloning this repo, cd into it and run npm install to install all the dependencies and dev-dependencies.
- Using the .env.sample content, create a .env in your root directory and fill in the fields.
- To run the test suit, run `npm run test` script
- To run on production run `npm start`

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#161785827
#### Questions:

### CODE REVIEW

**Review by ovieokeh — APPROVED** [review]
This all looks good. The Hound CI violations aren't nice though. Please fix them when you can.

**Review by oluseyianani — COMMENTED** [review]
@65black Adjusted the files and everything looks good. Thanks

**Review by desaawa — COMMENTED** [review]
Resolve conflicts and hound

**Comment by ovieokeh** [comment]
We already have the changes on this PR on the merged PRs. This PR is now redundant!

**Pull request closed without merging**
