### PR TITLE
#161290902 Allow users edit/view profile

### PR DESCRIPTION
**Pull request by Frediflexta**
#### What does this PR do?
* Enables a user the ability to edit their profile, including image upload
* Enables a user view other users profile but with no edit rights
* Enables a user the ability to delete their acount
#### Description of Task to be completed?
- enable user view profile
- enable authorised user edit profile
- setup cloudinary and muster for file uploads
- enable authorised user deactivate their account
- test for controllers
- rebased off 3 branches, to be in sync with the team
#### How should this be manually tested?
1. Clone repo
2. `npm install` to get all dependencies
3. Run `npm run test-dev` to run the test locally
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#161290902
#### Screenshots (if appropriate)
screen shot 2018-11-08 at 2 31 04 pm
screen shot 2018-11-08 at 2 31 30 pm

#### Questions:
N/A

### CODE REVIEW

**Review by oluseyianani — APPROVED** [review]
Good Job @Frediflexta you can see to it that the password of the user is not returned.

**Review by ovieokeh — APPROVED** [review]
Apart from the Hound violations, this looks perfect!

**Comment by desaawa** [comment]
Can you fix the failing Hound and Travis build?

**Review by ajimae — CHANGES_REQUESTED** [review]
Nice work @Frediflexta I think you shouldn't return the user's password in your return output on postman due to security reasons, I could see from the screenshot in the PR comment section where you returned the user's password, or is there a specific reason why you decide to display the user's password?

**Review by desaawa — APPROVED** [review]

**Comment by desaawa** [comment]
Update the postman image to show correct returns.

**Pull request merged**
