### PR TITLE
#161290910 Pagination Support for Articles

### PR DESCRIPTION
**Pull request by ajimae**
#### What does this PR do?

- Paginates the list of Articles in view (Pagination support for articles)

#### Description of Task to be completed?

  - Write test to check functionalities
  - Restructure folders and files tree
  - Modify routes folder, sequelizerc file to accommodate changes
  - Add validation for profile creation
  - Add validation for user login
  - Write test to test pagination features
  - Implement the feature proper
  - Test endpoint using postman

#### How should this be manually tested?

- Clone the repository, navigate into the cloned directory and run `npm install`
- Visit the url `localhost:3000/api/v1/articles/page/:pageNumber` where pageNumber can be any number from 1 upwards.

#### Any background context you want to provide?

- This is a skelectical functionality of the article pagination.
- When implementing the UI its flesh will be formed.

#### What are the relevant pivotal tracker stories?

[#161290910](https://www.pivotaltracker.com/story/show/161290910)

#### Screenshot

screen shot 2018-11-03 at 1 08 45 pm

screen shot 2018-11-03 at 1 03 44 pm

### CODE REVIEW

**Comment by oluseyianani** [comment]
Good job @ajimae, but 23 tests relating to creating articles are failing, can you try to fix that? It'll increase our coverage also.

**Review by ovieokeh — APPROVED** [review]
Superb work @ajimae. I've tested this on Postman and it works exactly like it should.

**Comment by ajimae** [comment]
> Good job @ajimae, but 23 tests relating to creating articles are failing, can you try to fix that? It'll increase our coverage also.

Fixed

**Review by desaawa — APPROVED** [review]

**Comment by desaawa** [comment]
@ajimae Please resolve the conflict here

**Comment by ajimae** [comment]
> @ajimae Please resolve the conflict here

The conflict has been resolved, you can proceed to merge the branch.

Thank you.

**Pull request merged**
