### PR TITLE
#161290897 Authenticate Users on Signup and Login

### PR DESCRIPTION
**Pull request by oluseyianani**
#### What does this PR do?
- Issue a valid token to a user on successful registration
- Issue a valid token to a user on successful login. The token is available on the response body as well as on the header with the key `x-token`.
- Middleware to validate a user token in other to successfully log in
- Passing tests to check for token availability, validation input, registration, and login functionality.
- User login functionality implemented
- User signup functionality implemented
- Upgrade babel configuration to accommodate runtime regeneration gotten as a result of using async await/promises.
- Adjust the test script on `package.json` to accommodate database migration.
- Adjust database attributes to accommodate the user's input.
#### Description of Task to be completed?
- `/POST 200 OK - /users/register` 
-- Required fields: `username, email, password, confirmPassword`.
- `/POST 200 OK - /users/login`
-- Required fields: `email, password`.
#### How should this be manually tested?
- After cloning this repo, cd into it and run `npm install` to install all the dependencies and dev-dependencies.
- Using the .env.sample content, create a `.env` in your `root directory` and fill in the fields.
- To run the test suit, run `npm run test-dev` script
- To run on the development mode, run `npm run dev` script

You can now go ahead to test the endpoints.

#### Any background context you want to provide?
- Your `PRIVATE_KEY` value has to be consistent after you have users stored in your database, the reason being the value will be checked against the password the user has provided, then, bcrypt will decrypt in other to confirm if the user's password on registration is the same.

#### What are the relevant pivotal tracker stories?
#161290897
#### Screenshots (if appropriate)
screen shot 2018-10-31 at 7 36 23 am

screen shot 2018-10-31 at 7 36 58 am

screen shot 2018-10-31 at 7 40 01 am

screen shot 2018-10-31 at 7 41 38 am

#### Questions:
N/A

### CODE REVIEW

**Review by ovieokeh — CHANGES_REQUESTED** [review]
Please resolve the Hound CI errors and Merge conflicts. Every other thing looks splendid. Good work man.

**Comment by oluseyianani** [comment]
@65black Yeah, currently resolving the merge conflict from the previous merge.

**Review by Frediflexta — COMMENTED** [review]
Any idea why those two tests are failing on travis? Nice work man, it's looking good.

**Review by hope-uwa — COMMENTED** [review]
@anasey01 I can see the .env file. it should be ignored

**Review by ovieokeh — APPROVED** [review]

**Comment by oluseyianani** [comment]
@uwaelpis an oversight. It's been taken out. Thanks.

**Comment by oluseyianani** [comment]
@Frediflexta I'm thinking it's the connection on elephantSQL. Everything is okay now.

**Review by desaawa — APPROVED** [review]

**Pull request merged**
