### PR TITLE
#161987549 Add Categorisation Functionality

### PR DESCRIPTION
**Pull request by ovieokeh**
#### What does this PR do?
This PR adds categorisation functionality to the Authors Haven API. Categorisation is now required for all articles being posted.

When creating a new article, a user must pick from the list of available categories on Authors Haven. New categories can only be added by an admin.

#### Description of Task to be completed?
- add a category to an article
- update category of an article
- move updating of an article tags to article update controller
- add migration for new category table
- add seeder for category table
- add tests for the new feature

#### How should this be manually tested?
1. #13 When creating an article, include a field called category and add a category
2. If you don't know the list of available categories, send the request anyway and it will be sent back to you in the response body

##### Changing the category of an existing article
1. Make a `PUT` request to `/articles/:slug` replacing `:slug` with the slug of the article you want to update
2. Add a field called `category` containing the new category you want to add to the article
3. You should get a success message when done correctly

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
#161987549

#### Screenshots (if appropriate)
screen shot 2018-11-16 at 2 24 49 pm
screen shot 2018-11-16 at 2 24 29 pm

#### Questions:
N/A

### CODE REVIEW

**Review by oluseyianani — APPROVED** [review]
Great job @65black

**Review by desaawa — CHANGES_REQUESTED** [review]
Resolve conflicts and get one more review.

**Review by hope-uwa — APPROVED** [review]
looks good to me. Great job @65black

**Review by ajimae — APPROVED** [review]
Nice work @65black, good initiative👌🏽

**Review by desaawa — APPROVED** [review]

**Pull request merged**
